default_stages: [commit, push]
exclude: ^tests/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml  # Attempts to load all yaml files to verify syntax.
      - id: end-of-file-fixer  # Makes sure files end in a newline and only a newline.
      - id: trailing-whitespace  # Trims trailing whitespace.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: debug-statements  # Check for debugger imports and py37+ breakpoint() calls in python source.
      - id: check-toml  # Attempts to load all TOML files to verify syntax.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        args: ["--exit-non-zero-on-fix", "--config=.ruff.toml"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["-m", "2"]

  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
