version: '3'
services:
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    command: uvicorn api.app:app --host 0.0.0.0 --port 5000 --reload
    tty: true
    stdin_open: true
